spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tsgl
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true

  servlet:
    multipart:
      max-file-size: 1024000000
      max-request-size: 1024000000


mybatis-plus:
  type-aliases-package: org.bupt.pojo
  # mapper-locations: classpath:com/mappers/*.xml
  mapper-locations: com/mappers/*.xml
  executor-type: simple # reuse 可以提高性能
  configuration:
    default-fetch-size: 20
    use-generated-keys: true # 是否返回主键
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  default-statement-timeout: 30  # 单位毫秒

excelAddress: /src/main/resources/excels/

bean-searcher:
  sql:
    default-mapping:
      redundant-suffixes: DTO
  params:
    pagination:
      default-size: 10
      start: 1
    separator: 'x'